# Generated by Django 5.2.11 on 2026-03-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninglog',
            name='code_language',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('csharp', 'C#'), ('cpp', 'C++'), ('c', 'C'), ('ruby', 'Ruby'), ('go', 'Go'), ('rust', 'Rust'), ('php', 'PHP'), ('swift', 'Swift'), ('kotlin', 'Kotlin'), ('sql', 'SQL'), ('html', 'HTML'), ('css', 'CSS'), ('typescript', 'TypeScript'), ('r', 'R'), ('matlab', 'MATLAB'), ('bash', 'Bash/Shell'), ('powershell', 'PowerShell'), ('json', 'JSON'), ('yaml', 'YAML'), ('xml', 'XML'), ('markdown', 'Markdown'), ('other', 'Other')], default='python', max_length=50, null=True),
        ),
    ]
